# Generated by Django 3.1.8 on 2021-05-16 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210504_1240"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_refreshed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("device", models.TextField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(unpack_ipv4=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="RefreshToken",),
    ]
